//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int id { get; set; }
        public int idGroup { get; set; }
        public int soCMND { get; set; }
        public string username { get; set; }
        public string pass { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual User User { get; set; }
    }
}
