//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public string maHoaDon { get; set; }
        public int cmndKhachHang { get; set; }
        public Nullable<double> soTien { get; set; }
        public Nullable<System.DateTime> ngayXuat { get; set; }
        public string hinhThucThanhToan { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
    }
}
