//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuDichVu
    {
        public string maPhieuDichVu { get; set; }
        public string maPhieuThuePhong { get; set; }
        public string maDichVu { get; set; }
        public Nullable<byte> soLuong { get; set; }
    
        public virtual DichVu DichVu { get; set; }
        public virtual PhieuThuePhong PhieuThuePhong { get; set; }
    }
}
